### PR TITLE
Instructions

### PR DESCRIPTION
**Pull request by cbattista**
This adds the features needed for #7.

@theochiu - I've tested this but can you take this for a spin - I wrote out a Test Script that you can use to determine whether it works or not - https://github.com/StanfordCosyne/screener/wiki/Tests---Instructions-and-practice

### CODE REVIEW

**Comment by theochiu** [comment]
I'll check it out this afternoon!

**Comment by cbattista** [comment]
great, thanks.  we're going to be heading to a school on Friday so I'd like
to try out the new system!

-C

**Comment by theochiu** [comment]
Do you want to leave to advance from practice if and only if 4/5 are correct? Right now it progresses you at 3 or more.

**Comment by cbattista** [comment]
Oh right, I think it's set to 3/5 right now.  Let me fix that and then I'll
merge the branch...

**Pull request merged**
